FROM busybox:latest
WORKDIR /app
RUN wget -O Yearning-2.2.1.linux-amd64.zip https://github-production-release-asset-2e65be.s3.amazonaws.com/107417113/fa97eb00-8876-11ea-92f1-bec577525cb9?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20200528%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200528T075836Z&X-Amz-Expires=300&X-Amz-Signature=83146085eab313eeb028d0cde7630b0ea61442482c796f5eb89e4afe5d49e0a5&X-Amz-SignedHeaders=host&actor_id=30437397&repo_id=107417113&response-content-disposition=attachment%3B%20filename%3DYearning-2.2.1.linux-amd64.zip&response-content-type=application%2Foctet-stream

# docker run -itd --name=busybox-downloadfile registry.cn-beijing.aliyuncs.com/huazhanghui/busybox:1.0