FROM busybox:latest
WORKDIR /app
RUN wget -O wkhtmltox-0.12.6-1.centos7.x86_64.rpm https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox-0.12.6-1.centos7.x86_64.rpm

# docker run -itd --name=busybox-downloadfile registry.cn-beijing.aliyuncs.com/huazhanghui/busybox:1.0