FROM busybox:latest
WORKDIR /app
RUN wget -O zabbix-app-4.0.2.zip https://github-production-release-asset-2e65be.s3.amazonaws.com/35092819/60f71780-25d5-11eb-99e8-846a6c103bef?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20210112%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210112T061016Z&X-Amz-Expires=300&X-Amz-Signature=238385a616ffd4a3f0b03f2c0ae8d32054aa5b29e170e01901f193392ce19a79&X-Amz-SignedHeaders=host&actor_id=27260207&key_id=0&repo_id=35092819&response-content-disposition=attachment%3B%20filename%3Dalexanderzobnin-zabbix-app-4.0.2.zip&response-content-type=application%2Foctet-stream

# docker run -itd --name=busybox-downloadfile registry.cn-beijing.aliyuncs.com/huazhanghui/busybox:1.0